name: ✨ Feature Request
description: Request a new feature or enhancement
title: "[FEAT]: "
labels: ["enhancement"]
assignees: ["neoxelox"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make the projects better 🤗
        Make sure there aren't any open/closed issues for this topic 😃

  - type: textarea
    id: feat-description
    attributes:
      label: Description
      description: Brief description of the feature or enhancement you are thinking about
    validations:
      required: true

  - type: textarea
    id: feat-extra
    attributes:
      label: Additional Information
      description: Some additional information on the feature request like proposed solutions, links, screenshots...
